sudo: required

language: generic 

services:
  - docker 

before_install:
  - docker build -t haxelegide/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haxelegide/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-east-1-161221511123
  bucket_path: "docker-react"

  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
