sudo: required

language: generic 

services:
  - docker 

before_install:
  - docker build -t haxelegide/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haxelegide/docker-react npm run test

